<?php namespace Redaxscript\Template; ?>

<!-- header -->

<header id="header" class="rs-header">

	<!-- title -->

	<?php if (Tag::getSetting('title')): ?>
		<h1 class="rs-title-header">
			<a href="<?php echo Tag::getRegistry('root'); ?>">
				<?php echo Tag::getSetting('title'); ?>
			</a>
		</h1>
	<?php endif; ?>

	<!-- menu -->

	<?php echo Tag::partial('ncss/menu-toggle.phtml'); ?>
</header>
