<?php namespace Redaxscript\Template; ?>

<!-- base -->

<?php echo Tag::base(); ?>

<!-- title -->

<?php echo Tag::title(Helper::getTitle()); ?>

<!-- meta -->

<?php echo Tag::meta()
	->init()
	->append('charset', Helper::getSetting('charset'))
	->append(['name' => 'author', 'content' => Helper::getSetting('author')])
	->append(['name' => 'generator', 'content' => Helper::getLanguage('_package')['name'] . ' ' . Helper::getLanguage('_package')['version']])
	->append(['name' => 'description', 'content' => Helper::getDescription()])
	->append(['name' => 'keywords', 'content' => Helper::getKeywords()])
	->append(['name' => 'robots', 'content' => Helper::getRobots()])
	->append(['name' => 'viewport', 'content' => 'width=device-width'])
	->append(['name' => 'theme-color', 'content' => '#282c34'])
	->append(['name' => 'apple-mobile-web-app-status-bar-stylecontent', 'content' => '#282c34']); ?>

<!-- link -->

<?php echo Tag::link()
	->init()
	->append(['href' => Helper::getCanonical(), 'rel' => 'canonical'])
	->append(['href' => 'data:image/png;base64,', 'rel' => 'shortcut icon'])
	->append(['href' => 'https://fonts.gstatic.com', 'rel' => 'preconnect'])
	->appendFile(
	[
		'https://fonts.googleapis.com/css2?family=PT+Sans+Narrow:wght@400;700',
		'templates/ncss/dist/styles/ncss.min.css'
	])
	->concat(); ?>

<!-- head script -->

<?php echo Tag::script()
	->init('head')
	->prependInline(Helper::getContent('assets/scripts/init.js'))
	->transportVar('rs', Helper::getTransport())
	->concat(); ?>