<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Helper::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass('rs-is-'); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'admin/head.phtml',
			'ncss/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<body class="rs-body">
		<?php $body = Tag::partial(
		[
			'ncss/header.phtml',
			'ncss/main.phtml',
			'admin/script.phtml',
			'ncss/script.phtml'
		]); ?>
		<?php echo Tag::partial(
		[
			'admin/panel.phtml',
			'admin/dashboard.phtml',
			'ncss/menu-status.phtml'
		]); ?>
		<div class="rs-has-menu">
			<?php echo $body; ?>
		</div>
	</body>
</html>
