<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Tag::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass('rs-is-'); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'templates/admin/head.phtml',
			'templates/ncss/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<body class="rs-body">
		<?php $body = Tag::partial(
		[
			'templates/ncss/main.phtml',
			'templates/admin/script.phtml',
			'templates/ncss/script.phtml'
		]); ?>
		<?php echo Tag::partial(
		[
			'templates/ncss/menu-status.phtml',
			'templates/admin/panel.phtml'
		]); ?>
		<div class="rs-has-menu">
			<?php echo $body; ?>
		</div>
	</body>
</html>
