<?php namespace Redaxscript\Template; ?>

<!-- main -->

<main id="main" class="rs-main">

	<!-- sidebar -->

	<?php echo Tag::partial('templates/ncss/sidebar.phtml'); ?>

	<!-- error -->

	<?php if (Tag::getRegistry('contentError')): ?>
		<?php echo Tag::partial('templates/ncss/error.phtml'); ?>

	<!-- else content -->

	<?php else: ?>
		<?php echo Tag::partial('templates/ncss/content.phtml'); ?>
	<?php endif; ?>

</main>