<?php namespace Redaxscript\Template; ?>

<!-- main -->

<main id="main" class="rs-main">

	<!-- error -->

	<?php if (Tag::getRegistry('contentError')): ?>
		<div class="rs-wrapper">
			<?php echo Tag::partial('templates/ncss/error.phtml'); ?>
		</div>

	<!-- else content and sidebar -->

	<?php else: ?>
		<div class="rs-wrapper rs-has-sidebar">
			<?php echo Tag::partial(
			[
				'templates/ncss/sidebar.phtml',
				'templates/ncss/content.phtml'
			]); ?>
		</div>
	<?php endif; ?>

</main>