<?php namespace Redaxscript\Template; ?>

<?php $navigationArray = include('ncss/helper/navigation.php'); ?>

<?php foreach ($navigationArray as $categoryArray): ?>

	<!-- list -->

	<ul class="rs-list-menu">
		<?php if ($categoryArray['children']): ?>
			<?php foreach ($categoryArray['children'] as $subArray): ?>
				<?php if (Helper::getRegistry('secondParameter') === $subArray['alias']): ?>
					<li class="rs-item-active">
				<?php else: ?>
					<li>
				<?php endif; ?>
					<a href="<?php echo Helper::getRegistry('parameterRoute') . $subArray['route']; ?>"><?php echo $subArray['title']; ?></a>

					<!-- children -->

					<?php if ($subArray['children']): ?>
						<ul class="rs-list-children">
							<?php foreach ($subArray['children'] as $articleArray): ?>
								<li>
									<a href="<?php echo Helper::getRegistry('parameterRoute') . $articleArray['route']; ?>"><?php echo $articleArray['title']; ?></a>
								</li>
							<?php endforeach; ?>
						</ul>
					<?php endif; ?>
				</li>
			<?php endforeach; ?>
		<?php endif; ?>
	</ul>
<?php endforeach; ?>