<?php namespace Redaxscript\Template; ?>

<aside id="sidebar" class="rs-fn-menu rs-sidebar">

	<!-- title -->

	<?php if (Helper::getSetting('title')): ?>
		<h1 class="rs-title-menu">
			<a href="<?php echo Helper::getRegistry('root'); ?>">
				<?php echo Helper::getSetting('title'); ?>
			</a>
		</h1>
	<?php endif; ?>

	<!-- navigation -->

	<?php include('ncss/helper/navigation.php'); ?>
	<?php include('ncss/navigation.phtml'); ?>

	<!-- search -->

	<?php echo Tag::searchForm(); ?>
</aside>
