<?php namespace Redaxscript\Template; ?>

<aside id="sidebar" class="rs-fn-menu rs-sidebar">

	<!-- branding -->

	<?php if (Tag::getSetting('title')): ?>
		<h1 class="rs-title-branding">
			<a href="<?php echo Tag::getRegistry('root'); ?>">
				<?php echo Tag::getSetting('title'); ?>
			</a>
		</h1>
	<?php endif; ?>

	<!-- navigation -->

	<?php include('templates/ncss/helper/navigation.php'); ?>
	<?php include('templates/ncss/navigation.phtml'); ?>
</aside>
